### ISSUE TITLE
Stack Trace when entering reg ID

### ISSUE THREAD

**Issue by jmdawson** [MidwestFurryFandom/art_show#59] opened 2018-05-24 01:54 UTC
Trish reported this. Put a reg ID in, or maybe the ID for an art show app, in the "I have already registered" field and it threw a 500.

```
500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 631, in respond
    self._do_respond(path_info)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 690, in _do_respond
    response.body = self.handler()
  File "/app/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in call
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in call
    return self.callable(*self.args, **self.kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 461, in with_timed
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 487, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 597, in with_restrictions
    return func(*args, **kwargs)
  File "/app/plugins/uber/uber/decorators.py", line 536, in with_rendering
    result = func(*args, **kwargs)
  File "/app/plugins/art_show/art_show/site_sections/art_show_admin.py", line 23, in form
    app = session.art_show_application(params)
  File "/app/plugins/uber/uber/models/__init__.py", line 50, in getter
    inst = self.query(model).filter_by(id=id).one()
  File "/app/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2890, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
```

**Comment by jmdawson** [comment] 2018-05-24 02:01
Also happens w/ a public_id value. Doesn't happen w/ '5' (get a blue validation error, instead)

**Comment by kitsuta** [comment] 2018-05-24 03:26
I can't reproduce this bug, even on staging.

I did find a different 500 error; pushing a fix for that now.

**Comment by jmdawson** [comment] 2018-05-24 16:34
ping @hugmonster to update the ticket to reflect what she did to generate it. I can't duplicate it either; I assumed my 500 was the same 500, but it was not.

**Comment by kitsuta** [comment] 2018-09-11 01:08
Tried a few different UUIDs, cannot reproduce. Closing.

**Closed by kitsuta** 2018-09-11 01:08 UTC
Labels: bug
