### ISSUE TITLE
Checking in an Artist and the City is still a drop down.  

### ISSUE THREAD

**Issue by Hugmonster** [MidwestFurryFandom/art_show#198] opened 2018-11-09 21:18 UTC
Artist - Nine Elevenzies

Got pop up to select a state and choose Ohio .  Choose Save and Check in and it not displaying the state selected.

It looks like it has saved somewhere as it shows when I go back into the artist application, Pieces and print the checkin from there

**Comment by kitsuta** [comment] 2018-11-13 00:14
I cannot reproduce this on my local server, but I can reproduce it on staging.

**Comment by kitsuta** [comment] 2018-11-16 01:04
Fixed by https://github.com/MidwestFurryFandom/art_show/pull/210. Thank goodness.

**Closed by kitsuta** 2018-11-16 01:04 UTC
