### ISSUE TITLE
Art show payment page charges incorrect price

### ISSUE THREAD

**Issue by SkylerRingtail** [MidwestFurryFandom/art_show#47] opened 2017-10-26 01:17 UTC
(Can currently be seen with artist named "Guest O'Honor)

This panelist has apparently already paid for their badge, and has requested 4 panels for a total of $20 (no override). The payment page, however, is only charging $15 (denoted both by the descriptive text, and the credit card payment window).

![image](https://user-images.githubusercontent.com/28108495/32030543-3ead2058-b9c1-11e7-8fd6-86b8a5df8232.png)

![image](https://user-images.githubusercontent.com/28108495/32030547-4ab7996e-b9c1-11e7-8ef9-beabb4905ae0.png)

![image](https://user-images.githubusercontent.com/28108495/32030555-549e8da2-b9c1-11e7-8f42-699e0bfb72ec.png)

(Payment page URL: http://rams.test.furfest.org/rams/art_show_applications/edit?id=c416c5a3-8ae4-40c8-b3bc-2b8e68541114 )

**Comment by kitsuta** [comment] 2017-10-29 17:09
This was caused by https://github.com/MidwestFurryFandom/rams/issues/172. It is now fixed on staging.

**Closed** 2017-10-31 14:13 UTC
